### ISSUE TITLE
wine collapse

### ISSUE THREAD

**Issue by 530126162** [codehz/ElementZero#144] opened 2020-08-21 09:29 UTC
![TL(D(TEW~Z2_9Y{1}PBCJ F](https://user-images.githubusercontent.com/70012803/90875538-e2bf1680-e3d3-11ea-9045-735a2613527f.png)

**Comment by 530126162** [comment] 2020-08-24 02:26
No one knows？？？？

**Comment by 530126162** [comment] 2020-08-24 02:27
help me!!!

**Comment by madeofstown** [comment] 2020-08-24 03:05
Which instructions did you use to install and which build are you using.

**Comment by 530126162** [comment] 2020-08-24 03:09
![image](https://user-images.githubusercontent.com/70012803/90999788-25623800-e5fa-11ea-8070-95f2d923a214.png)
This is installed
The wine version is 5.0.2

**Comment by 530126162** [comment] 2020-08-24 03:11
> 您使用了哪些说明进行安装以及使用了哪些内部版本。

ElementZero-v0.1.0-6-win64
This is installed
The wine version is 5.0.2

**Comment by madeofstown** [comment] 2020-08-24 03:14
Make sure that you have vcruntime140_1.dll in the same folder as bedrock_server_mod.exe

**Comment by 530126162** [comment] 2020-08-24 03:16
> 确保在与bedrock_server_mod.exe相同的文件夹中有vcruntime140_1.dll

![image](https://user-images.githubusercontent.com/70012803/91000164-234ca900-e5fb-11ea-8b01-4e27a58ec696.png)
of course

**Comment by madeofstown** [comment] 2020-08-24 03:17
Try docker method maybe.

**Comment by 530126162** [comment] 2020-08-24 03:20
> Try docker method maybe.

I won't. do you have a detailed method

**Comment by madeofstown** [comment] 2020-08-24 03:21
Wait. Are you using Windows?

**Comment by 530126162** [comment] 2020-08-24 03:23
> 等待。您在使用Windows吗？

I won't. do you have a detailed method

**Comment by madeofstown** [comment] 2020-08-24 03:23
For docker use this https://elementzero.flarum.cloud/d/27-linux-auto-install-script

**Comment by 530126162** [comment] 2020-08-24 05:55
> 对于docker使用此https://elementzero.flarum.cloud/d/27-linux-auto-install-script

Thank you very much.

**Comment by madeofstown** [comment] 2020-08-24 12:56
Glad I could help. 😁

**Comment by elijahr2411** [comment] 2020-08-28 14:56
Closing because it seems the issue is solved. Feel free to reopen if it's not.

**Closed as completed by elijahr2411** 2020-08-28 14:56 UTC
Labels: bug
